import { CelestialObject, CelestialType } from "@/types";

export const CELESTIAL_TYPES: CelestialType[] = ["planet", "star", "exoplanet", "moon", "dwarf planet"];

export const DISCOVERY_METHODS: string[] = ["Direct observation", "Radial velocity", "Transit photometry", "Gravitational microlensing", "Imaging", "Astrometry", "Ancient observation"];

export const BASE_CELESTIAL_DATA: CelestialObject[] = [
  {
    id: "mercury",
    name: "Mercury",
    type: "planet",
    designation: "Sol I",
    distanceFromSun: 0.39,
    distanceUnit: "AU",
    mass: 0.055,
    massUnit: "M⊕",
    radius: 2439.7,
    radiusUnit: "km",
    gravity: 3.7,
    orbitalPeriod: 88,
    rotationPeriod: 1407.6,
    temperature: { min: -180, max: 430, avg: 167 },
    discoveryDate: "Ancient",
    discoveryMethod: "Ancient observation",
    atmosphere: ["Oxygen", "Sodium", "Hydrogen", "Helium"],
    composition: ["Iron core", "Silicate mantle"],
    rings: false,
    moons: 0,
    color: "#8c8c8c",
    accentColor: "#b5a07a",
    summary: "The smallest planet in the Solar System and closest to the Sun. Its surface is heavily cratered and resembles Earth's Moon.",
    facts: ["A year on Mercury is just 88 Earth days", "Mercury has no atmosphere to retain heat", "Its iron core makes up 75% of its radius"],
    missions: [
      { name: "Mariner 10", year: 1974, type: "Flyby", status: "Complete", detail: "First spacecraft to visit Mercury, mapping 45% of the surface across three flybys." },
      { name: "MESSENGER", year: 2011, type: "Orbiter", status: "Complete", detail: "Orbited Mercury for four years, confirming water ice in permanently shadowed craters." },
      { name: "BepiColombo", year: 2025, type: "Orbiter", status: "En Route", detail: "Joint ESA/JAXA mission currently in transit, expected to begin orbital science operations." },
    ],
  },
  {
    id: "venus",
    name: "Venus",
    type: "planet",
    designation: "Sol II",
    distanceFromSun: 0.72,
    distanceUnit: "AU",
    mass: 0.815,
    massUnit: "M⊕",
    radius: 6051.8,
    radiusUnit: "km",
    gravity: 8.87,
    orbitalPeriod: 225,
    rotationPeriod: 5832.5,
    temperature: { min: 462, max: 462, avg: 462 },
    discoveryDate: "Ancient",
    discoveryMethod: "Ancient observation",
    atmosphere: ["Carbon dioxide", "Nitrogen", "Sulfuric acid clouds"],
    composition: ["Iron core", "Rocky mantle", "Basaltic crust"],
    rings: false,
    moons: 0,
    color: "#e8cda0",
    accentColor: "#d4a843",
    summary: "Often called Earth's twin due to similar size, Venus has a runaway greenhouse effect creating the hottest surface in the Solar System.",
    facts: ["Venus rotates backward compared to most planets", "A day on Venus is longer than its year", "Surface pressure is 90 times that of Earth"],
    missions: [
      { name: "Venera 7", year: 1970, type: "Lander", status: "Complete", detail: "First spacecraft to successfully land on another planet and transmit data from the surface." },
      { name: "Magellan", year: 1990, type: "Orbiter", status: "Complete", detail: "Mapped 98% of the Venusian surface using synthetic aperture radar." },
      { name: "VERITAS", year: 2031, type: "Orbiter", status: "Planned", detail: "NASA Discovery mission to map Venus in high resolution and study its geology." },
    ],
  },
  {
    id: "earth",
    name: "Earth",
    type: "planet",
    designation: "Sol III",
    distanceFromSun: 1.0,
    distanceUnit: "AU",
    mass: 1.0,
    massUnit: "M⊕",
    radius: 6371,
    radiusUnit: "km",
    gravity: 9.81,
    orbitalPeriod: 365.25,
    rotationPeriod: 24,
    temperature: { min: -89, max: 57, avg: 15 },
    discoveryDate: "N/A",
    discoveryMethod: "Direct observation",
    atmosphere: ["Nitrogen", "Oxygen", "Argon", "Carbon dioxide"],
    composition: ["Iron-nickel core", "Silicate mantle", "Crust"],
    rings: false,
    moons: 1,
    color: "#4a90d9",
    accentColor: "#2d6eb5",
    summary: "The only known planet to harbor life. Earth's liquid water, magnetic field, and atmosphere create conditions uniquely suited for biology.",
    facts: ["Earth's rotation is gradually slowing", "The planet's magnetic field shields it from solar wind", "70% of the surface is covered by water"],
    missions: [
      { name: "Apollo 17", year: 1972, type: "Crewed", status: "Complete", detail: "Last crewed lunar mission; captured the iconic 'Blue Marble' photograph of Earth." },
      { name: "Terra (EOS)", year: 1999, type: "Orbiter", status: "Active", detail: "Flagship Earth observing satellite studying climate, weather, and environmental change." },
      { name: "PACE", year: 2024, type: "Orbiter", status: "Active", detail: "Studying ocean color and atmospheric aerosols to understand climate interactions." },
    ],
  },
  {
    id: "mars",
    name: "Mars",
    type: "planet",
    designation: "Sol IV",
    distanceFromSun: 1.52,
    distanceUnit: "AU",
    mass: 0.107,
    massUnit: "M⊕",
    radius: 3389.5,
    radiusUnit: "km",
    gravity: 3.72,
    orbitalPeriod: 687,
    rotationPeriod: 24.6,
    temperature: { min: -140, max: 20, avg: -63 },
    discoveryDate: "Ancient",
    discoveryMethod: "Ancient observation",
    atmosphere: ["Carbon dioxide", "Nitrogen", "Argon"],
    composition: ["Iron oxide surface", "Basaltic rock", "Iron core"],
    rings: false,
    moons: 2,
    color: "#c1440e",
    accentColor: "#e05d2c",
    summary: "The Red Planet is the most explored body in the Solar System beyond Earth, with evidence of ancient water and ongoing robotic exploration.",
    facts: ["Olympus Mons is the tallest volcano in the Solar System", "Mars has seasons similar to Earth", "Its thin atmosphere is 95% carbon dioxide"],
    missions: [
      { name: "Viking 1", year: 1976, type: "Lander", status: "Complete", detail: "First successful Mars lander, operated for over six years on the surface." },
      { name: "Curiosity", year: 2012, type: "Rover", status: "Active", detail: "Car-sized rover exploring Gale Crater, studying habitability and geology." },
      { name: "Perseverance", year: 2021, type: "Rover", status: "Active", detail: "Collecting samples for future return to Earth and testing oxygen production." },
    ],
  },
  {
    id: "jupiter",
    name: "Jupiter",
    type: "planet",
    designation: "Sol V",
    distanceFromSun: 5.2,
    distanceUnit: "AU",
    mass: 317.8,
    massUnit: "M⊕",
    radius: 69911,
    radiusUnit: "km",
    gravity: 24.79,
    orbitalPeriod: 4333,
    rotationPeriod: 9.9,
    temperature: { min: -145, max: -108, avg: -110 },
    discoveryDate: "Ancient",
    discoveryMethod: "Ancient observation",
    atmosphere: ["Hydrogen", "Helium", "Methane", "Ammonia"],
    composition: ["Hydrogen/helium atmosphere", "Metallic hydrogen", "Dense core"],
    rings: true,
    moons: 95,
    color: "#c8a55a",
    accentColor: "#d4b86a",
    summary: "The largest planet in the Solar System, a gas giant with a mass greater than all other planets combined. Its Great Red Spot is a storm larger than Earth.",
    facts: ["Jupiter has the shortest day of any planet at 9.9 hours", "The Great Red Spot has raged for at least 350 years", "Jupiter's magnetic field is 20,000 times stronger than Earth's"],
    missions: [
      { name: "Pioneer 10", year: 1973, type: "Flyby", status: "Complete", detail: "First spacecraft to traverse the asteroid belt and make direct observations of Jupiter." },
      { name: "Galileo", year: 1995, type: "Orbiter", status: "Complete", detail: "First spacecraft to orbit Jupiter, deploying an atmospheric probe." },
      { name: "Juno", year: 2016, type: "Orbiter", status: "Active", detail: "Polar orbit studying Jupiter's composition, gravity field, and magnetosphere." },
    ],
  },
  {
    id: "saturn",
    name: "Saturn",
    type: "planet",
    designation: "Sol VI",
    distanceFromSun: 9.54,
    distanceUnit: "AU",
    mass: 95.16,
    massUnit: "M⊕",
    radius: 58232,
    radiusUnit: "km",
    gravity: 10.44,
    orbitalPeriod: 10759,
    rotationPeriod: 10.7,
    temperature: { min: -178, max: -139, avg: -140 },
    discoveryDate: "Ancient",
    discoveryMethod: "Ancient observation",
    atmosphere: ["Hydrogen", "Helium", "Methane"],
    composition: ["Hydrogen/helium atmosphere", "Metallic hydrogen", "Rocky core"],
    rings: true,
    moons: 146,
    color: "#e8d5a3",
    accentColor: "#c9b87c",
    summary: "Famous for its spectacular ring system, Saturn is a gas giant with a density low enough to float on water.",
    facts: ["Saturn's rings are mostly water ice particles", "Wind speeds can reach 1,800 km/h", "Saturn could fit 764 Earths inside it"],
    missions: [
      { name: "Voyager 1", year: 1980, type: "Flyby", status: "Complete", detail: "Provided first detailed images of Saturn's rings and discovered several new moons." },
      { name: "Cassini-Huygens", year: 2004, type: "Orbiter", status: "Complete", detail: "Orbited Saturn for 13 years; Huygens probe landed on Titan." },
      { name: "Dragonfly", year: 2034, type: "Rotorcraft", status: "Planned", detail: "Nuclear-powered rotorcraft to explore Titan's surface and prebiotic chemistry." },
    ],
  },
  {
    id: "uranus",
    name: "Uranus",
    type: "planet",
    designation: "Sol VII",
    distanceFromSun: 19.2,
    distanceUnit: "AU",
    mass: 14.54,
    massUnit: "M⊕",
    radius: 25362,
    radiusUnit: "km",
    gravity: 8.69,
    orbitalPeriod: 30687,
    rotationPeriod: 17.2,
    temperature: { min: -224, max: -205, avg: -220 },
    discoveryDate: "1781",
    discoveryMethod: "Direct observation",
    atmosphere: ["Hydrogen", "Helium", "Methane"],
    composition: ["Icy mantle", "Hydrogen/helium atmosphere", "Rocky core"],
    rings: true,
    moons: 28,
    color: "#72b5c7",
    accentColor: "#5a9db5",
    summary: "An ice giant tilted on its side, Uranus orbits the Sun with an extreme axial tilt of 98 degrees, causing extreme seasonal variation.",
    facts: ["Uranus rotates on its side at 98° tilt", "It was the first planet discovered with a telescope", "Its blue-green color comes from methane ice clouds"],
    missions: [
      { name: "Voyager 2", year: 1986, type: "Flyby", status: "Complete", detail: "Only spacecraft to visit Uranus, discovering 10 new moons and 2 new rings." },
      { name: "Uranus Orbiter & Probe", year: 2032, type: "Orbiter", status: "Proposed", detail: "Highest-priority flagship mission recommended by the 2023 Planetary Science Decadal Survey." },
    ],
  },
  {
    id: "neptune",
    name: "Neptune",
    type: "planet",
    designation: "Sol VIII",
    distanceFromSun: 30.07,
    distanceUnit: "AU",
    mass: 17.15,
    massUnit: "M⊕",
    radius: 24622,
    radiusUnit: "km",
    gravity: 11.15,
    orbitalPeriod: 60190,
    rotationPeriod: 16.1,
    temperature: { min: -218, max: -200, avg: -214 },
    discoveryDate: "1846",
    discoveryMethod: "Astrometry",
    atmosphere: ["Hydrogen", "Helium", "Methane"],
    composition: ["Icy mantle", "Hydrogen/helium atmosphere", "Rocky core"],
    rings: true,
    moons: 16,
    color: "#3a5fcd",
    accentColor: "#4a7ae0",
    summary: "The most distant planet in the Solar System, Neptune was the first planet located through mathematical prediction rather than direct observation.",
    facts: ["Neptune has the strongest sustained winds—up to 2,100 km/h", "One Neptune year equals 165 Earth years", "It was predicted mathematically before being observed"],
    missions: [{ name: "Voyager 2", year: 1989, type: "Flyby", status: "Complete", detail: "Only spacecraft to visit Neptune, revealing the Great Dark Spot and active geysers on Triton." }],
  },
  {
    id: "proxima-b",
    name: "Proxima Centauri b",
    type: "exoplanet",
    designation: "Proxima Cen b",
    distanceFromSun: 4.24,
    distanceUnit: "ly",
    mass: 1.17,
    massUnit: "M⊕",
    radius: 7160,
    radiusUnit: "km",
    gravity: 10.9,
    orbitalPeriod: 11.2,
    rotationPeriod: null,
    temperature: { min: -39, max: -39, avg: -39 },
    discoveryDate: "2016",
    discoveryMethod: "Radial velocity",
    atmosphere: ["Unknown"],
    composition: ["Rocky (estimated)"],
    rings: false,
    moons: null,
    color: "#7a4e3a",
    accentColor: "#a0674d",
    summary: "The closest known exoplanet to Earth, orbiting within the habitable zone of Proxima Centauri, the nearest star to the Sun.",
    facts: ["Located just 4.24 light-years from Earth", "Orbits in the habitable zone of its red dwarf star", "A year lasts only 11.2 Earth days"],
    missions: [{ name: "Breakthrough Starshot", year: 2036, type: "Flyby", status: "Proposed", detail: "Proposed fleet of light-sail nanocraft accelerated by ground-based lasers to reach Proxima at 20% light speed." }],
  },
  {
    id: "trappist-1e",
    name: "TRAPPIST-1e",
    type: "exoplanet",
    designation: "TRAPPIST-1 e",
    distanceFromSun: 39.6,
    distanceUnit: "ly",
    mass: 0.692,
    massUnit: "M⊕",
    radius: 5797,
    radiusUnit: "km",
    gravity: 9.15,
    orbitalPeriod: 6.1,
    rotationPeriod: null,
    temperature: { min: -48, max: -22, avg: -27 },
    discoveryDate: "2017",
    discoveryMethod: "Transit photometry",
    atmosphere: ["Under investigation"],
    composition: ["Rocky, possibly iron-rich core"],
    rings: false,
    moons: null,
    color: "#4a6b8a",
    accentColor: "#5d85a8",
    summary: "One of seven Earth-sized planets in the TRAPPIST-1 system, considered the most promising candidate for habitability in the system.",
    facts: ["Part of a system with 7 rocky planets", "Located in the habitable zone", "JWST is actively studying its atmosphere"],
    missions: [{ name: "JWST Observations", year: 2023, type: "Telescope", status: "Active", detail: "James Webb Space Telescope conducting transmission spectroscopy to characterize the atmosphere." }],
  },
  {
    id: "kepler-442b",
    name: "Kepler-442b",
    type: "exoplanet",
    designation: "KOI-4742.01",
    distanceFromSun: 1206,
    distanceUnit: "ly",
    mass: 2.36,
    massUnit: "M⊕",
    radius: 8610,
    radiusUnit: "km",
    gravity: 12.4,
    orbitalPeriod: 112.3,
    rotationPeriod: null,
    temperature: { min: -40, max: 0, avg: -2.7 },
    discoveryDate: "2015",
    discoveryMethod: "Transit photometry",
    atmosphere: ["Unknown"],
    composition: ["Possibly rocky-water world"],
    rings: false,
    moons: null,
    color: "#3a7d5f",
    accentColor: "#4d9e78",
    summary: "A super-Earth exoplanet with one of the highest Earth Similarity Index scores ever recorded, orbiting in its star's habitable zone.",
    facts: ["Earth Similarity Index of 0.84", "Over 1,200 light-years from Earth", "Receives about 70% of the light Earth gets from the Sun"],
    missions: [{ name: "Kepler Space Telescope", year: 2015, type: "Telescope", status: "Complete", detail: "Discovered via the Kepler mission's transit method observations." }],
  },
  {
    id: "titan",
    name: "Titan",
    type: "moon",
    designation: "Saturn VI",
    distanceFromSun: 9.54,
    distanceUnit: "AU",
    mass: 0.0225,
    massUnit: "M⊕",
    radius: 2574.7,
    radiusUnit: "km",
    gravity: 1.35,
    orbitalPeriod: 15.9,
    rotationPeriod: 15.9,
    temperature: { min: -179, max: -179, avg: -179 },
    discoveryDate: "1655",
    discoveryMethod: "Direct observation",
    atmosphere: ["Nitrogen", "Methane", "Ethane"],
    composition: ["Water ice", "Rocky interior", "Subsurface ocean"],
    rings: false,
    moons: 0,
    color: "#c2a64e",
    accentColor: "#d4b85e",
    summary: "Saturn's largest moon and the only moon in the Solar System with a dense atmosphere. It features liquid methane lakes and rivers on its surface.",
    facts: ["Only moon with a substantial atmosphere", "Has liquid methane seas on its surface", "Larger than the planet Mercury"],
    missions: [
      { name: "Huygens Probe", year: 2005, type: "Lander", status: "Complete", detail: "First landing in the outer Solar System; descended through Titan's atmosphere for 2.5 hours." },
      { name: "Dragonfly", year: 2034, type: "Rotorcraft", status: "Planned", detail: "Will fly through Titan's thick atmosphere studying prebiotic chemistry at multiple sites." },
    ],
  },
  {
    id: "europa",
    name: "Europa",
    type: "moon",
    designation: "Jupiter II",
    distanceFromSun: 5.2,
    distanceUnit: "AU",
    mass: 0.008,
    massUnit: "M⊕",
    radius: 1560.8,
    radiusUnit: "km",
    gravity: 1.31,
    orbitalPeriod: 3.55,
    rotationPeriod: 3.55,
    temperature: { min: -220, max: -160, avg: -171 },
    discoveryDate: "1610",
    discoveryMethod: "Direct observation",
    atmosphere: ["Oxygen (trace)"],
    composition: ["Ice shell", "Subsurface ocean", "Silicate mantle"],
    rings: false,
    moons: 0,
    color: "#c4bfae",
    accentColor: "#9e9885",
    summary: "One of Jupiter's Galilean moons, Europa is believed to harbor a global saltwater ocean beneath its icy crust, making it a prime target in the search for extraterrestrial life.",
    facts: ["May have more liquid water than all of Earth's oceans", "Its ice shell is estimated to be 15–25 km thick", "Plumes of water vapor have been detected erupting from the surface"],
    missions: [
      { name: "Galileo", year: 1995, type: "Orbiter", status: "Complete", detail: "Provided the strongest evidence for a subsurface ocean through magnetic field measurements." },
      { name: "Europa Clipper", year: 2024, type: "Orbiter", status: "Active", detail: "Conducting detailed reconnaissance of Europa's ice shell and ocean through 49 planned flybys." },
    ],
  },
  {
    id: "enceladus",
    name: "Enceladus",
    type: "moon",
    designation: "Saturn II",
    distanceFromSun: 9.54,
    distanceUnit: "AU",
    mass: 0.000018,
    massUnit: "M⊕",
    radius: 252.1,
    radiusUnit: "km",
    gravity: 0.113,
    orbitalPeriod: 1.37,
    rotationPeriod: 1.37,
    temperature: { min: -240, max: -128, avg: -201 },
    discoveryDate: "1789",
    discoveryMethod: "Direct observation",
    atmosphere: ["Water vapor", "Nitrogen", "Carbon dioxide"],
    composition: ["Ice shell", "Subsurface ocean", "Silicate core"],
    rings: false,
    moons: 0,
    color: "#e8e8e8",
    accentColor: "#b0d0e0",
    summary: "A small but remarkable moon of Saturn with active geysers shooting water vapor and ice particles into space from its south polar region.",
    facts: ["Geysers feed material into Saturn's E ring", "Hydrothermal vents may exist on its ocean floor", "Organic molecules have been detected in its plumes"],
    missions: [
      { name: "Cassini", year: 2005, type: "Orbiter", status: "Complete", detail: "Discovered water plumes and flew through them, detecting complex organic molecules." },
      { name: "Enceladus Orbilander", year: 2038, type: "Orbiter/Lander", status: "Proposed", detail: "Concept mission to orbit then land, directly sampling plume material for biosignatures." },
    ],
  },
  {
    id: "sirius",
    name: "Sirius A",
    type: "star",
    designation: "α Canis Majoris",
    distanceFromSun: 8.6,
    distanceUnit: "ly",
    mass: 2.06,
    massUnit: "M☉",
    radius: 1189000,
    radiusUnit: "km",
    gravity: null,
    orbitalPeriod: null,
    rotationPeriod: null,
    temperature: { min: 9940, max: 9940, avg: 9940 },
    discoveryDate: "Ancient",
    discoveryMethod: "Ancient observation",
    atmosphere: ["Hydrogen", "Helium"],
    composition: ["Hydrogen fusion core", "Helium"],
    rings: false,
    moons: null,
    color: "#cfe0ff",
    accentColor: "#aac8ff",
    summary: "The brightest star in Earth's night sky, Sirius is a binary system consisting of a main-sequence star and a faint white dwarf companion.",
    facts: ["25.4 times more luminous than the Sun", "Its companion Sirius B is a white dwarf", "Known as the 'Dog Star' in Canis Major"],
    missions: [{ name: "Hipparcos", year: 1989, type: "Telescope", status: "Complete", detail: "ESA astrometry satellite that precisely measured Sirius's distance and proper motion." }],
  },
  {
    id: "betelgeuse",
    name: "Betelgeuse",
    type: "star",
    designation: "α Orionis",
    distanceFromSun: 650,
    distanceUnit: "ly",
    mass: 16.5,
    massUnit: "M☉",
    radius: 617100000,
    radiusUnit: "km",
    gravity: null,
    orbitalPeriod: null,
    rotationPeriod: null,
    temperature: { min: 3600, max: 3600, avg: 3600 },
    discoveryDate: "Ancient",
    discoveryMethod: "Ancient observation",
    atmosphere: ["Hydrogen", "Helium", "Molecular shells"],
    composition: ["Helium-fusing core", "Hydrogen envelope"],
    rings: false,
    moons: null,
    color: "#ff6040",
    accentColor: "#e04830",
    summary: "A red supergiant in Orion nearing the end of its life. Expected to explode as a supernova within the next 100,000 years.",
    facts: ["If placed at the Sun's position, it would engulf Jupiter's orbit", "Its brightness varies on an irregular cycle", "The 'Great Dimming' of 2019–2020 was caused by a dust cloud"],
    missions: [
      { name: "ALMA Observations", year: 2017, type: "Telescope", status: "Complete", detail: "Atacama Large Millimeter Array resolved the star's photosphere directly for the first time." },
      { name: "JWST Monitoring", year: 2024, type: "Telescope", status: "Active", detail: "Infrared observations studying mass-loss events and surface convection cells." },
    ],
  },
  {
    id: "pluto",
    name: "Pluto",
    type: "dwarf planet",
    designation: "134340 Pluto",
    distanceFromSun: 39.5,
    distanceUnit: "AU",
    mass: 0.0022,
    massUnit: "M⊕",
    radius: 1188.3,
    radiusUnit: "km",
    gravity: 0.62,
    orbitalPeriod: 90560,
    rotationPeriod: 153.3,
    temperature: { min: -240, max: -218, avg: -229 },
    discoveryDate: "1930",
    discoveryMethod: "Direct observation",
    atmosphere: ["Nitrogen", "Methane", "Carbon monoxide"],
    composition: ["Ice and rock", "Nitrogen ice plains", "Water ice mountains"],
    rings: false,
    moons: 5,
    color: "#c4a882",
    accentColor: "#a88e6a",
    summary: "Once classified as the ninth planet, Pluto is now recognized as the most famous dwarf planet, featuring a heart-shaped nitrogen glacier called Tombaugh Regio.",
    facts: ["Pluto's heart-shaped glacier is larger than Texas", "It has a thin atmosphere that freezes and falls as snow", "Pluto and its moon Charon are tidally locked to each other"],
    missions: [{ name: "New Horizons", year: 2015, type: "Flyby", status: "Complete", detail: "First spacecraft to visit Pluto, revealing a geologically active world with mountains of water ice." }],
  },
  {
    id: "ceres",
    name: "Ceres",
    type: "dwarf planet",
    designation: "1 Ceres",
    distanceFromSun: 2.77,
    distanceUnit: "AU",
    mass: 0.00016,
    massUnit: "M⊕",
    radius: 473,
    radiusUnit: "km",
    gravity: 0.28,
    orbitalPeriod: 1682,
    rotationPeriod: 9.07,
    temperature: { min: -106, max: -34, avg: -73 },
    discoveryDate: "1801",
    discoveryMethod: "Direct observation",
    atmosphere: ["Water vapor (transient)"],
    composition: ["Clay minerals", "Water ice", "Carbonates"],
    rings: false,
    moons: 0,
    color: "#8a8a7a",
    accentColor: "#a0a090",
    summary: "The largest object in the asteroid belt and the only dwarf planet in the inner Solar System. Ceres features mysterious bright spots of sodium carbonate.",
    facts: ["Contains about a third of the asteroid belt's total mass", "Bright spots in Occator crater are salt deposits", "May have a subsurface layer of briny water"],
    missions: [{ name: "Dawn", year: 2015, type: "Orbiter", status: "Complete", detail: "First mission to orbit a dwarf planet, studying Ceres's surface composition and internal structure." }],
  },
  {
    id: "io",
    name: "Io",
    type: "moon",
    designation: "Jupiter I",
    distanceFromSun: 5.2,
    distanceUnit: "AU",
    mass: 0.015,
    massUnit: "M⊕",
    radius: 1821.6,
    radiusUnit: "km",
    gravity: 1.8,
    orbitalPeriod: 1.77,
    rotationPeriod: 1.77,
    temperature: { min: -183, max: -143, avg: -163 },
    discoveryDate: "1610",
    discoveryMethod: "Direct observation",
    atmosphere: ["Sulfur dioxide"],
    composition: ["Silicate rock", "Iron core", "Sulfur surface"],
    rings: false,
    moons: 0,
    color: "#d4c040",
    accentColor: "#e0d050",
    summary: "The most volcanically active body in the Solar System, with over 400 active volcanoes powered by intense tidal heating from Jupiter.",
    facts: ["Over 400 active volcanoes on its surface", "Tidal forces from Jupiter generate immense internal heat", "Its surface is export constantly reshaped by volcanic activity"],
    missions: [
      { name: "Galileo", year: 1995, type: "Orbiter", status: "Complete", detail: "Made multiple close flybys, observing active volcanic eruptions and lava flows." },
      { name: "Juno Extended", year: 2024, type: "Orbiter", status: "Active", detail: "Close flybys providing highest-resolution images of Io's volcanic surface." },
    ],
  },
  {
    id: "kepler-22b",
    name: "Kepler-22b",
    type: "exoplanet",
    designation: "KOI-87.01",
    distanceFromSun: 635,
    distanceUnit: "ly",
    mass: 9.1,
    massUnit: "M⊕",
    radius: 15290,
    radiusUnit: "km",
    gravity: 12.5,
    orbitalPeriod: 290,
    rotationPeriod: null,
    temperature: { min: -11, max: -11, avg: -11 },
    discoveryDate: "2011",
    discoveryMethod: "Transit photometry",
    atmosphere: ["Unknown"],
    composition: ["Possibly ocean world or mini-Neptune"],
    rings: false,
    moons: null,
    color: "#5a8ab0",
    accentColor: "#6d9fc7",
    summary: "The first confirmed exoplanet in the habitable zone of a Sun-like star. Its size suggests it may be a water world or possess a thick atmosphere.",
    facts: ["First habitable zone planet found by Kepler around a Sun-like star", "About 2.4 times Earth's radius", "Orbital period is 290 days, similar to Earth's year"],
    missions: [{ name: "Kepler Space Telescope", year: 2011, type: "Telescope", status: "Complete", detail: "Confirmed as the first transiting planet in the habitable zone of a Sun-like star." }],
  },
];

const EXTRA_MOONS: CelestialObject[] = [
  {
    id: "moon",
    name: "Moon",
    type: "moon",
    designation: "Earth I",
    parentId: "earth",
    distanceFromSun: 1.0,
    distanceUnit: "AU",
    mass: 0.0123,
    massUnit: "M⊕",
    radius: 1737.4,
    radiusUnit: "km",
    gravity: 1.62,
    orbitalPeriod: 27.3,
    rotationPeriod: 655.7,
    temperature: { min: -173, max: 127, avg: -20 },
    discoveryDate: "Ancient",
    discoveryMethod: "Ancient observation",
    atmosphere: ["Exosphere (trace)"],
    composition: ["Anorthositic crust", "Basaltic maria", "Iron-rich core (small)"],
    rings: false,
    moons: 0,
    color: "#b8b8b8",
    accentColor: "#d0d0d0",
    summary: "Earth’s natural satellite with heavily cratered highlands and basaltic maria. It stabilizes Earth’s axial tilt and drives tides.",
    facts: ["Tidally locked to Earth", "Apollo missions returned lunar samples", "Extremely thin exosphere"],
    missions: [{ name: "Apollo Program", year: 1969, type: "Crewed", status: "Complete", detail: "Human landings and sample return from the lunar surface." }],
  },
  {
    id: "phobos",
    name: "Phobos",
    type: "moon",
    designation: "Mars I",
    parentId: "mars",
    distanceFromSun: 1.52,
    distanceUnit: "AU",
    mass: 0.000000017,
    massUnit: "M⊕",
    radius: 11.266,
    radiusUnit: "km",
    gravity: 0.0057,
    orbitalPeriod: 0.3189,
    rotationPeriod: 7.65,
    temperature: { min: -4, max: -4, avg: -4 },
    discoveryDate: "1877",
    discoveryMethod: "Direct observation",
    atmosphere: ["None"],
    composition: ["Carbonaceous rock (suspected)", "Regolith"],
    rings: false,
    moons: 0,
    color: "#7f6f63",
    accentColor: "#a08f7f",
    summary: "The larger and closer of Mars’ two moons, Phobos orbits so close it rises in the west and sets in the east.",
    facts: ["Orbit is slowly decaying", "Surface has grooves and a large crater (Stickney)", "Possible captured asteroid"],
    missions: [],
  },
  {
    id: "deimos",
    name: "Deimos",
    type: "moon",
    designation: "Mars II",
    parentId: "mars",
    distanceFromSun: 1.52,
    distanceUnit: "AU",
    mass: 0.0000000024,
    massUnit: "M⊕",
    radius: 6.2,
    radiusUnit: "km",
    gravity: 0.003,
    orbitalPeriod: 1.262,
    rotationPeriod: 30.3,
    temperature: { min: -40, max: -40, avg: -40 },
    discoveryDate: "1877",
    discoveryMethod: "Direct observation",
    atmosphere: ["None"],
    composition: ["Carbonaceous rock (suspected)", "Regolith"],
    rings: false,
    moons: 0,
    color: "#6e625a",
    accentColor: "#8e7f74",
    summary: "Mars’ smaller outer moon, Deimos has a smoother appearance due to regolith filling craters.",
    facts: ["Low gravity", "Likely captured", "Very dark surface"],
    missions: [],
  },
  {
    id: "ganymede",
    name: "Ganymede",
    type: "moon",
    designation: "Jupiter III",
    parentId: "jupiter",
    distanceFromSun: 5.2,
    distanceUnit: "AU",
    mass: 0.025,
    massUnit: "M⊕",
    radius: 2634.1,
    radiusUnit: "km",
    gravity: 1.43,
    orbitalPeriod: 7.15,
    rotationPeriod: 171.6,
    temperature: { min: -163, max: -113, avg: -153 },
    discoveryDate: "1610",
    discoveryMethod: "Direct observation",
    atmosphere: ["Oxygen (trace)"],
    composition: ["Water ice crust", "Silicate mantle", "Metallic core"],
    rings: false,
    moons: 0,
    color: "#a9a39b",
    accentColor: "#d6d1c8",
    summary: "The largest moon in the Solar System, Ganymede has its own magnetic field and likely a subsurface ocean.",
    facts: ["Larger than Mercury", "Has intrinsic magnetosphere", "Mix of dark and bright terrains"],
    missions: [],
  },
  {
    id: "callisto",
    name: "Callisto",
    type: "moon",
    designation: "Jupiter IV",
    parentId: "jupiter",
    distanceFromSun: 5.2,
    distanceUnit: "AU",
    mass: 0.018,
    massUnit: "M⊕",
    radius: 2410.3,
    radiusUnit: "km",
    gravity: 1.24,
    orbitalPeriod: 16.69,
    rotationPeriod: 400.6,
    temperature: { min: -193, max: -108, avg: -139 },
    discoveryDate: "1610",
    discoveryMethod: "Direct observation",
    atmosphere: ["Carbon dioxide (trace)"],
    composition: ["Ice and rock mixture"],
    rings: false,
    moons: 0,
    color: "#6f665f",
    accentColor: "#a09890",
    summary: "A heavily cratered Galilean moon with an ancient surface and possible subsurface ocean.",
    facts: ["One of the most cratered bodies known", "Geologically inactive compared to Europa/Io", "Dark surface rich in carbon compounds"],
    missions: [],
  },
  {
    id: "triton",
    name: "Triton",
    type: "moon",
    designation: "Neptune I",
    parentId: "neptune",
    distanceFromSun: 30.07,
    distanceUnit: "AU",
    mass: 0.0036,
    massUnit: "M⊕",
    radius: 1353.4,
    radiusUnit: "km",
    gravity: 0.78,
    orbitalPeriod: 5.88,
    rotationPeriod: 141.1,
    temperature: { min: -235, max: -235, avg: -235 },
    discoveryDate: "1846",
    discoveryMethod: "Direct observation",
    atmosphere: ["Nitrogen (thin)"],
    composition: ["Nitrogen ice", "Water ice", "Rocky interior"],
    rings: false,
    moons: 0,
    color: "#cfd7de",
    accentColor: "#e7eef5",
    summary: "Neptune’s largest moon, Triton orbits retrograde and shows evidence of cryovolcanism and nitrogen geysers.",
    facts: ["Retrograde orbit", "Likely captured Kuiper Belt object", "Surface includes nitrogen and methane ices"],
    missions: [{ name: "Voyager 2", year: 1989, type: "Flyby", status: "Complete", detail: "Revealed active geysers and varied icy terrain." }],
  },
  {
    id: "charon",
    name: "Charon",
    type: "moon",
    designation: "Pluto I",
    parentId: "pluto",
    distanceFromSun: 39.5,
    distanceUnit: "AU",
    mass: 0.00026,
    massUnit: "M⊕",
    radius: 606,
    radiusUnit: "km",
    gravity: 0.288,
    orbitalPeriod: 6.387,
    rotationPeriod: 153.3,
    temperature: { min: -220, max: -180, avg: -200 },
    discoveryDate: "1978",
    discoveryMethod: "Direct observation",
    atmosphere: ["None"],
    composition: ["Water ice", "Rock"],
    rings: false,
    moons: 0,
    color: "#a8a3a0",
    accentColor: "#d0cbc8",
    summary: "Pluto’s largest moon; Pluto and Charon form a close binary system and are tidally locked.",
    facts: ["Tidally locked pair", "Canyon systems and varied terrain", "Discovered by James Christy"],
    missions: [{ name: "New Horizons", year: 2015, type: "Flyby", status: "Complete", detail: "Mapped Charon’s surface and geology during Pluto flyby." }],
  },
  // Smaller Pluto moons (minimal) ✅ this must be INSIDE the array
  ...(["nix", "hydra", "kerberos", "styx"] as const).map(
    (id, i): CelestialObject => ({
      id,
      name: id[0].toUpperCase() + id.slice(1),
      type: "moon",
      designation: `Pluto ${i + 2}`,
      parentId: "pluto",
      distanceFromSun: 39.5,
      distanceUnit: "AU",
      mass: 0.000000001,
      massUnit: "M⊕",
      radius: 20 + i * 5,
      radiusUnit: "km",
      gravity: 0.01,
      orbitalPeriod: 20 + i * 5,
      rotationPeriod: null,
      temperature: { min: -240, max: -210, avg: -230 },
      discoveryDate: i < 2 ? "2005" : "2011",
      discoveryMethod: "Imaging",
      atmosphere: ["None"],
      composition: ["Ice and rock"],
      rings: false,
      moons: 0,
      color: "#8b8b8b",
      accentColor: "#b0b0b0",
      summary: "A small irregular moon in the Pluto system, discovered via deep imaging.",
      facts: ["Very small body", "Likely formed from impact debris", "Irregular shape"],
      missions: [
        {
          name: "New Horizons",
          year: 2015,
          type: "Flyby",
          status: "Complete",
          detail: "Imaged Pluto’s small moons during the encounter.",
        },
      ],
    }),
  ),
];

/**
 * Links planets -> moons (uses your existing IDs where possible).
 * Note: You already have io, europa, titan, enceladus in your base data; this file just links them.
 */
export const MOON_LINKS: Record<string, string[]> = {
  earth: ["moon"],
  mars: ["phobos", "deimos"],
  jupiter: ["io", "europa", "ganymede", "callisto"],
  saturn: ["titan", "enceladus"],
  neptune: ["triton"],
  pluto: ["charon", "nix", "hydra", "kerberos", "styx"],
};

export const CELESTIAL_DATA: CelestialObject[] = [...BASE_CELESTIAL_DATA.map((o) => (MOON_LINKS[o.id] ? { ...o, moonIds: MOON_LINKS[o.id] } : o)), ...EXTRA_MOONS];

// Handy index map for lookups
export const CELESTIAL_INDEX: Record<string, CelestialObject> = Object.fromEntries(CELESTIAL_DATA.map((o) => [o.id, o]));
